namespace PapertrailFor7DTD.SDK {
    public enum Facility {
        kernel = 0,
        userlevel = 1,
        mailsystem = 2,
        systemdaemons = 3,
        authorization = 4,
        syslogd = 5,
        lineprinter = 6,
        networknews = 7,
        UUCPsubsystem = 8,
        clockdaemon = 9,
        security = 10,
        FTPdaemon = 11,
        NTPsubsystem = 12,
        logaudit = 13,
        logalert = 14,
        note2 = 15,
        local0 = 16,
        local1 = 17,
        local2 = 18,
        local3 = 19,
        local4 = 20,
        local5 = 21,
        local6 = 22,
        local7 = 23,
    }
}